In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('bengaluru_house_prices.csv')
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [3]:
df.shape

(13320, 9)

In [4]:
df.groupby('area_type')['area_type'].agg('count')

area_type
Built-up  Area          2418
Carpet  Area              87
Plot  Area              2025
Super built-up  Area    8790
Name: area_type, dtype: int64

In [5]:
df.drop(['area_type', 'society', 'availability'], axis='columns', inplace=True)
df.head()

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [6]:
df.isnull().sum()

location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [7]:
df[df['location'].isnull()]

    location   size total_sqft  bath  balcony  price
568      NaN  3 BHK       1600   3.0      2.0   86.0

In [8]:
df.drop(df[df['location'].isnull()].index, inplace=True)

In [9]:
df['balcony'].fillna(0, inplace=True)
df.head()

C:\Users\thaku\AppData\Local\Temp\ipykernel_77608\4135350000.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['balcony'].fillna(0, inplace=True)

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [10]:
df.isnull().sum()

location       0
size          16
total_sqft     0
bath          73
balcony        0
price          0
dtype: int64

In [11]:
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [12]:
df['bhk'] = df['size'].str.split(' ').str[0]
df.head()

                   location       size total_sqft  bath  balcony   price bhk
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07   2
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00   4
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00   3
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00   3
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00   2

In [13]:
df2 = df.dropna()
df2.head()

                   location       size total_sqft  bath  balcony   price bhk
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07   2
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00   4
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00   3
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00   3
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00   2

In [14]:
df2.drop(['size'], axis='columns', inplace=True)
df2.head()

C:\Users\thaku\AppData\Local\Temp\ipykernel_77608\2694622649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(['size'], axis='columns', inplace=True)

                   location total_sqft  bath  balcony   price bhk
0  Electronic City Phase II       1056   2.0      1.0   39.07   2
1          Chikka Tirupathi       2600   5.0      3.0  120.00   4
2               Uttarahalli       1440   2.0      3.0   62.00   3
3        Lingadheeranahalli       1521   3.0      1.0   95.00   3
4                  Kothanur       1200   2.0      1.0   51.00   2

In [15]:
df2['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2067,), dtype=object)

In [16]:
def total_sqft_to_float(x):
    try:
        tokens = x.split('-')
        if len(tokens) == 2:
            return (float(tokens[0]) + float(tokens[1])) / 2
        return float(x)
    except:
        return None

In [17]:
df3 = df2.copy()
df3['total_sqft'] = df3['total_sqft'].apply(total_sqft_to_float)
df3.head()

                   location  total_sqft  bath  balcony   price bhk
0  Electronic City Phase II      1056.0   2.0      1.0   39.07   2
1          Chikka Tirupathi      2600.0   5.0      3.0  120.00   4
2               Uttarahalli      1440.0   2.0      3.0   62.00   3
3        Lingadheeranahalli      1521.0   3.0      1.0   95.00   3
4                  Kothanur      1200.0   2.0      1.0   51.00   2

In [18]:
df4 = df3.copy()
df4['price_per_sqft'] = (df4['price'] * 100000 / df4['total_sqft']).round(2)
df4.head()

,location,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2,3699.81
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4,4615.38
2,Uttarahalli,1440.0,2.0,3.0,62.00,3,4305.56
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3,6245.89
4,Kothanur,1200.0,2.0,1.0,51.00,2,4250.00

In [19]:
df4.location.unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], shape=(1304,), dtype=object)

In [20]:
df4.location = df4.location.apply(lambda x: x.strip())
df5 = df4.copy()
location_stats = df4.groupby('location')['location'].agg('count').sort_values(ascending=False)
df5.location = df5.location.apply(lambda x: 'other' if location_stats[x] <= 10 else x)
df5.head()

,location,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2,3699.81
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4,4615.38
2,Uttarahalli,1440.0,2.0,3.0,62.00,3,4305.56
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3,6245.89
4,Kothanur,1200.0,2.0,1.0,51.00,2,4250.00

In [21]:
df5['bhk'] = df5['bhk'].astype(int)
df5[df5.total_sqft / df5.bhk < 300].head()

               location  total_sqft  bath  balcony  price  bhk  price_per_sqft
9                 other      1020.0   6.0      0.0  370.0    6        36274.51
45           HSR Layout       600.0   9.0      0.0  200.0    8        33333.33
58        Murugeshpalya      1407.0   4.0      1.0  150.0    6        10660.98
68  Devarachikkanahalli      1350.0   7.0      0.0   85.0    8         6296.30
70                other       500.0   3.0      2.0  100.0    3        20000.00

In [22]:
df6 = df5[~(df5.total_sqft / df5.bhk < 300)]
df6.shape

(12502, 7)

In [23]:
df6.price_per_sqft.describe()

count     12456.000000
mean       6308.502836
std        4168.127366
min         267.830000
25%        4210.530000
50%        5294.120000
75%        6916.670000
max      176470.590000
Name: price_per_sqft, dtype: float64

In [24]:
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        reduced_df = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft <= (m + st))]
        df_out = pd.concat([df_out, reduced_df], ignore_index=True)
    return df_out
df7 = remove_pps_outliers(df6)
df7.shape

(10241, 7)

In [25]:
def remove_bhk_outliers(df):
    exclude_indices = np.array([])
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(exclude_indices, bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values)
    return df.drop(exclude_indices, axis='index')
df8 = remove_bhk_outliers(df7)
df8.shape

(7329, 7)

In [26]:
df9 = df8[df8['bath'] < df8['bhk'] + 2]
df9.shape

(7251, 7)

In [27]:
df9.drop(['price_per_sqft'], axis='columns', inplace=True)
df9.head()

C:\Users\thaku\AppData\Local\Temp\ipykernel_77608\161200043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df9.drop(['price_per_sqft'], axis='columns', inplace=True)

              location  total_sqft  bath  balcony  price  bhk
0  1st Block Jayanagar      2850.0   4.0      1.0  428.0    4
1  1st Block Jayanagar      1630.0   3.0      2.0  194.0    3
2  1st Block Jayanagar      1875.0   2.0      3.0  235.0    3
3  1st Block Jayanagar      1200.0   2.0      0.0  130.0    3
4  1st Block Jayanagar      1235.0   2.0      2.0  148.0    2

In [32]:
dummies = pd.get_dummies(df9.location, dtype=int)

In [33]:
df10 = pd.concat([df9.drop('location', axis='columns'), dummies.drop('other', axis='columns')], axis='columns')
df10.head()

,total_sqft,bath,balcony,price,bhk,1st Block Jayanagar,1st Phase JP Nagar,2nd Phase Judicial Layout,2nd Stage Nagarbhavi,5th Block Hbr Layout,...,Vijayanagar,Vishveshwarya Layout,Vishwapriya Layout,Vittasandra,Whitefield,Yelachenahalli,Yelahanka,Yelahanka New Town,Yelenahalli,Yeshwanthpur
0,2850.0,4.0,1.0,428.0,4,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1630.0,3.0,2.0,194.0,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1875.0,2.0,3.0,235.0,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1200.0,2.0,0.0,130.0,3,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1235.0,2.0,2.0,148.0,2,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
df10.shape

(7251, 246)

In [36]:
X = df10.drop(['price'], axis='columns')
y = df10.price

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

In [ ]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
# from sklearn.tree import DecisionTreeRegressor
# from sklearn.linear_model import Lasso

# def find_best_model_using_gridsearchcv(X, y):
#     algorithms = {
#         'linear_regression': {
#             'model': LinearRegression(),
#             'parameters': {
#                 'fit_intercept': [True, False]
#             }
#         },
#         'lasso': {
#             'model': Lasso(),
#             'parameters': {
#                 'alpha': [1, 2],
#                 'selection': ['random', 'cyclic']
#             }
#         },
#         'decision_tree': {
#             'model': DecisionTreeRegressor(),
#             'parameters': {
#                 'criterion': ['squared_error', 'absolute_error'],
#                 'splitter': ['best', 'random']
#             }
#         }
#     }
#     scores = []
#     cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
#     for algorithm_name, config in algorithms.items():
#         gs = GridSearchCV(config['model'], config['parameters'], cv=cv, return_train_score=False)
#         gs.fit(X, y)
#         scores.append({
#             'model': algorithm_name,
#             'best_score': gs.best_score_,
#             'best_params': gs.best_params_
#         })
#     return pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])

# find_best_model_using_gridsearchcv(X, y)

,model,best_score,best_params
0,linear_regression,0.819043,{'fit_intercept': False}
1,lasso,0.687552,"{'alpha': 1, 'selection': 'random'}"
2,decision_tree,0.707949,"{'criterion': 'squared_error', 'splitter': 'ra..."

In [45]:
lr_model = LinearRegression()
lr_model.fit(X_train, y_train)
lr_model.score(X_test, y_test)

0.8454334113886304

In [46]:
def predict_price(location, total_sqft, bath, bhk, balcony):
    loc_index = np.where(X.columns == location)[0][0]
    x = np.zeros(len(X.columns))
    x[0] = total_sqft
    x[1] = bath
    x[2] = balcony
    x[3] = bhk
    if loc_index >= 0:
        x[loc_index] = 1
    return lr_model.predict([x])[0]

In [57]:
prediction = predict_price('1st Phase JP Nagar', 1000, 2, 2, 1)
print(f"Prediction: {prediction:.2f}")

Prediction: 83.98

C:\Users\thaku\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [58]:
import pickle
with open('banglore_home_prices_model.pickle', 'wb') as f:
    pickle.dump(lr_model, f)

In [59]:
import json
columns = {
    'data_columns': [col.lower() for col in X.columns]
}
with open("columns.json", "w") as f:
    f.write(json.dumps(columns))