In [58]:
import pandas as pd
import numpy as np

In [60]:
df = pd.read_csv('bengaluru_house_prices.csv')
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [61]:
df.shape

(13320, 9)

In [62]:
df.groupby('area_type')['area_type'].agg('count')

area_type
Built-up  Area          2418
Carpet  Area              87
Plot  Area              2025
Super built-up  Area    8790
Name: area_type, dtype: int64

In [63]:
df.drop(['area_type', 'society', 'availability'], axis='columns', inplace=True)
df.head()

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [64]:
df.isnull().sum()

location        1
size           16
total_sqft      0
bath           73
balcony       609
price           0
dtype: int64

In [65]:
df[df['location'].isnull()]

    location   size total_sqft  bath  balcony  price
568      NaN  3 BHK       1600   3.0      2.0   86.0

In [66]:
df.drop(df[df['location'].isnull()].index, inplace=True)

In [67]:
df['balcony'].fillna(0, inplace=True)
df.head()

C:\Users\thaku\AppData\Local\Temp\ipykernel_16148\4135350000.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['balcony'].fillna(0, inplace=True)

                   location       size total_sqft  bath  balcony   price
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00

In [68]:
df.isnull().sum()

location       0
size          16
total_sqft     0
bath          73
balcony        0
price          0
dtype: int64

In [69]:
df['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '4 BHK', '6 Bedroom', '3 Bedroom',
       '1 BHK', '1 RK', '1 Bedroom', '8 Bedroom', '2 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', nan, '9 Bedroom', '27 BHK', '10 Bedroom', '11 Bedroom',
       '10 BHK', '19 BHK', '16 BHK', '43 Bedroom', '14 BHK', '8 BHK',
       '12 Bedroom', '13 BHK', '18 Bedroom'], dtype=object)

In [70]:
df['bhk'] = df['size'].str.split(' ').str[0]
df.head()

                   location       size total_sqft  bath  balcony   price bhk
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07   2
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00   4
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00   3
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00   3
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00   2

In [71]:
df2 = df.dropna()
df2.head()

                   location       size total_sqft  bath  balcony   price bhk
0  Electronic City Phase II      2 BHK       1056   2.0      1.0   39.07   2
1          Chikka Tirupathi  4 Bedroom       2600   5.0      3.0  120.00   4
2               Uttarahalli      3 BHK       1440   2.0      3.0   62.00   3
3        Lingadheeranahalli      3 BHK       1521   3.0      1.0   95.00   3
4                  Kothanur      2 BHK       1200   2.0      1.0   51.00   2

In [72]:
df2.drop(['size'], axis='columns', inplace=True)
df2.head()

C:\Users\thaku\AppData\Local\Temp\ipykernel_16148\2694622649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.drop(['size'], axis='columns', inplace=True)

                   location total_sqft  bath  balcony   price bhk
0  Electronic City Phase II       1056   2.0      1.0   39.07   2
1          Chikka Tirupathi       2600   5.0      3.0  120.00   4
2               Uttarahalli       1440   2.0      3.0   62.00   3
3        Lingadheeranahalli       1521   3.0      1.0   95.00   3
4                  Kothanur       1200   2.0      1.0   51.00   2

In [73]:
df2['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(2067,), dtype=object)

In [74]:
def total_sqft_to_float(x):
    try:
        tokens = x.split('-')
        if len(tokens) == 2:
            return (float(tokens[0]) + float(tokens[1])) / 2
        return float(x)
    except:
        return None

In [75]:
df3 = df2.copy()
df3['total_sqft'] = df3['total_sqft'].apply(total_sqft_to_float)
df3.head()

                   location  total_sqft  bath  balcony   price bhk
0  Electronic City Phase II      1056.0   2.0      1.0   39.07   2
1          Chikka Tirupathi      2600.0   5.0      3.0  120.00   4
2               Uttarahalli      1440.0   2.0      3.0   62.00   3
3        Lingadheeranahalli      1521.0   3.0      1.0   95.00   3
4                  Kothanur      1200.0   2.0      1.0   51.00   2

In [79]:
df4 = df3.copy()
df4['price_per_sqft'] = (df4['price'] * 100000 / df4['total_sqft']).round(2)
df4.head()

,location,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2,3699.81
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4,4615.38
2,Uttarahalli,1440.0,2.0,3.0,62.00,3,4305.56
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3,6245.89
4,Kothanur,1200.0,2.0,1.0,51.00,2,4250.00

In [81]:
df4.location.unique()

array(['Electronic City Phase II', 'Chikka Tirupathi', 'Uttarahalli', ...,
       '12th cross srinivas nagar banshankari 3rd stage',
       'Havanur extension', 'Abshot Layout'], shape=(1304,), dtype=object)

In [86]:
df4.location = df4.location.apply(lambda x: x.strip())
df5 = df4.copy()
location_stats = df4.groupby('location')['location'].agg('count').sort_values(ascending=False)
df5.location = df5.location.apply(lambda x: 'other' if location_stats[x] <= 10 else x)
df5.head()

,location,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Electronic City Phase II,1056.0,2.0,1.0,39.07,2,3699.81
1,Chikka Tirupathi,2600.0,5.0,3.0,120.00,4,4615.38
2,Uttarahalli,1440.0,2.0,3.0,62.00,3,4305.56
3,Lingadheeranahalli,1521.0,3.0,1.0,95.00,3,6245.89
4,Kothanur,1200.0,2.0,1.0,51.00,2,4250.00